version: "3.8"

services:
    wordpress:
        image: "wordpress:latest"
        volumes:
            - "wordpress-files:/var/www/html"
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=$USER_WORDPRESS
            - WORDPRESS_DB_PASSWORD=$PASSWORD_WORDPRESS
            - WORDPRESS_DB_NAME=wordpress
        depends_on:
            - mysql
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1"]
            interval: 2s
            timeout: 10s
            retries: 10
        ports:
            - "8080:80" # Exposition du port pour WordPress
        user: "www-data" # Assure que WordPress fonctionne sous l'utilisateur correct

    mysql:
        image: "mysql:8"
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD_ROOT
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=$USER_WORDPRESS
            - MYSQL_PASSWORD=$PASSWORD_WORDPRESS
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
            interval: 5s
            timeout: 20s
            retries: 10

    pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8070:80"
        environment:
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD_ROOT

    ftp:
        build:
            context: ./ftp
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        environment:
            - USERS=ftpuser|strongpassword|/var/www/html
        volumes:
            - "wordpress-files:/var/www/html"
        depends_on:
            - wordpress

volumes:
    wordpress-files:
        driver: local
    mysql-data:
        driver: local
