version: "3.8"

services:
    wordpress:
        image: "wordpress:latest"
        volumes:
            - "wordpress-files:/var/www/html"
        environment:
            - SERVICE_FQDN_WORDPRESS
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
            - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
            - WORDPRESS_DB_NAME=wordpress
        depends_on:
            - mysql
        healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://127.0.0.1"
            interval: 2s
            timeout: 10s
            retries: 10

    mysql:
        image: "mysql:8"
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=$WORDPRESS_DB_USER
            - MYSQL_PASSWORD=$WORDPRESS_DB_PASSWORD
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-h"
                - 127.0.0.1
            interval: 5s
            timeout: 20s
            retries: 10

    pma:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PASSWORD=$WORDPRESS_DB_PASSWORD

    ftp:
        build:
            context: ./ftp # Chemin relatif au Dockerfile
        network_mode: host
        ports:
            - "21:21" # Port FTP standard
            - "21000-21010:21000-21010" # Ports passifs FTP
        environment:
            - USERS=ftp_user_graphandco|1FTPvmQ2tl@@AZ|/var/www/html
            - UID=33 # Correspond à l'UID de www-data
            - GID=33 # Correspond au GID de www-data
        volumes:
            - "wordpress-files:/var/www/html" # Partage avec WordPress

volumes:
    wordpress-files:
        driver: local # Volume local pour persister les fichiers WordPress
    mysql-data:
        driver: local # Volume local pour les données MySQL
