version: "3.8"

services:
    wordpress:
        image: "wordpress:latest"
        volumes:
            - "wordpress-files:/var/www/html"
        environment:
            - SERVICE_FQDN_WORDPRESS
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=$USER_WORDPRESS
            - WORDPRESS_DB_PASSWORD=$PASSWORD_WORDPRESS
            - WORDPRESS_DB_NAME=wordpress
        depends_on:
            - mysql
        healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://127.0.0.1"
            interval: 2s
            timeout: 10s
            retries: 10

    mysql:
        image: "mysql:8"
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD_ROOT
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=$USER_WORDPRESS
            - MYSQL_PASSWORD=$PASSWORD_WORDPRESS
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-h"
                - 127.0.0.1
            interval: 5s
            timeout: 20s
            retries: 10

    pma:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        ports:
            - "8070:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PASSWORD=$MYSQL_PASSWORD_ROOT

    ftp:
        build:
            context: ./ftp
            args:
                UID: ${FTP_UID:-33} # UID par défaut 33
                GID: ${FTP_GID:-33} # GID par défaut 33
        network_mode: host
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        environment:
            - USERS=ftpusergraphandco|1FTPvmQ2tl@@AZ|/var/www/html
        volumes:
            - "wordpress-files:/var/www/html"

volumes:
    wordpress-files:
        driver: local
    mysql-data:
        driver: local
